apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: node-app
      version: blue
  template:
    metadata:
      labels:
        app: node-app
        version: blue
    spec:
      containers:
      - name: node-app
        image: ghcr.io/tauqeerahmad5201/nodeapp-rollup:v1
        ports:
        - containerPort: 3000