apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-green
spec:
  replicas: 5
  selector:
    matchLabels:
      app: node-app
      version: green
  template:
    metadata:
      labels:
        app: node-app
        version: green
    spec:
      containers:
      - name: node-app
        image: ghcr.io/tauqeerahmad5201/nodeapp-rollup:v2
        ports:
        - containerPort: 3000