apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort
  selector:
    app: node-app
    version: <mention any version > #blue or green
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000